on: [push]

jobs:
  argocd-app-health:
    runs-on: ubuntu-latest
    name: Check application status
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: samsongudise/argocd-app-healthcheck@v13
      with:
        application: 'cluster-autoscaler'
        servername: 'argocd.dev.clearbit.io'
        version: 1.0
        username: ${{ secrets.ARGOCD_USERNAME }}
        password: ${{ secrets.ARGOCD_PASSWORD }}
    - run: echo HealthStatus ${{ steps.foo.outputs.HealthStatus }} 
      shell: bash
